### ISSUE TITLE
Error when running pytest.

### ISSUE THREAD

**Issue by danass** [scivision/PyLivestream#15]
I'm in Mac Sierra 10.12 
Running Python 3.6.3
I checked for the depencies, i have ffmpeg also installed, seems like its correct though.

It's very long, but i just show the more striking errors that appears at the end of the log.

```
E               FileNotFoundError: [Errno 2] No such file or directory: 'ffplay': 'ffplay'

/Applications/Anaconda/anaconda3/lib/python3.6/subprocess.py:1344: FileNotFoundError
------------------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------------------
starting RTMP listener.  Press   q   in this terminal to end stream.
------------------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------------------
WARNING:root:assuming 480p input.
=================================================================== 1 failed, 10 passed, 7 error in 2.45 seconds ===================================================================
silence:PyLivestream danass$ 
```

**Comment by danass** [comment]
Ok i succeded in solving by reinstalling ffmpeg with the --with-sdl2 parameter. So now ffplay exist in the binaries of the mac.
But here are the new errors : 
```

/Applications/Anaconda/anaconda3/lib/python3.6/subprocess.py:291: CalledProcessError
------------------------------------------------------------------------------ Captured stdout setup -------------------------------------------------------------------------------
starting RTMP listener
------------------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Applications/Anaconda/anaconda3/bin/WebcamLivestream", line 7, in <module>
    from Webcam import main
ModuleNotFoundError: No module named 'Webcam'
======================================================================= 8 failed, 10 passed in 3.40 seconds ================================================================
```

Actually it finds none of the modules.

**Comment by danass** [comment]
```
silence:PyLivestream danass$ python Microphone.py 
Press Enter to go live on ['localhost'].    Or Ctrl C to abort.
starting RTMP listener.  Press   q   in this terminal to end stream.

 ffmpeg -v error -loop 1 -f image2 -i doc/logo.png -c:v libx264 -pix_fmt yuv420p -preset veryfast -b:v 800k -r 30.0 -g 60.0 -maxrate 800k -bufsize 400k -shortest -strict experimental -f flv rtmp://localhost 

Unrecognized option 'preset'.
Error splitting the argument list: Option not found
Traceback (most recent call last):
  File "Microphone.py", line 49, in <module>
    main()
  File "Microphone.py", line 45, in main
    s.golive()
  File "/Users/danass/Assadon/livestream/PyLivestream/pylivestream/__init__.py", line 202, in golive
    next(self.streams[unify_streams(self.streams)].startlive(sinks))
  File "/Users/danass/Assadon/livestream/PyLivestream/pylivestream/__init__.py", line 84, in startlive
    utils.run(self.cmd)
  File "/Users/danass/Assadon/livestream/PyLivestream/pylivestream/utils.py", line 14, in run
    subprocess.check_call(cmd)
  File "/Applications/Anaconda/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ffmpeg', '-v', 'error', '-loop', '1', '-f', 'image2', '-i', 'doc/logo.png', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-preset', 'veryfast', '-b:v', '800k', '-r', '30.0', '-g', '60.0', '-maxrate', '800k', '-bufsize', '400k', '-shortest', '-strict', 'experimental', '-f', 'flv', 'rtmp://localhost']' returned non-zero exit status 1.
silence:PyLivestream danass$ 

```

**Comment by danass** [comment]
Ok so i removed all version of ffmpeg from my computer.
i git cloned, did a ./configure && make && make install. The error was the same.
I downloaded compiled binaries and place them in both local bin folders and anaconda bin folder.
Now ffmpeg seems to be working but.

When i do pytest, 
the camera turns on and off but in the end i still get this type of messages 
`ModuleNotFoundError: No module named 'Webcam'`

Here is the beginnig of the log: 
```
silence:PyLivestream danass$ pytest 
====================================================================================== test session starts ======================================================================================
platform darwin -- Python 3.6.3, pytest-3.2.1, py-1.4.34, pluggy-0.4.0
rootdir: /Users/danass/Assadon/livestream/PyLivestream, inifile:
collected 18 items                                                                                                                                                                               

tests/test_class.py ...
tests/test_disk.py .
tests/test_filein.py ..FF
tests/test_microphone.py ..FF
tests/test_screen.py .FF
tests/test_webcam.py .FF

```

**Comment by scivision** [comment]
I suggest trying to fiddle directly with the command output from Pyivestream in terminal. Do the commands suggested by FFMPEG for Mac work
https://trac.ffmpeg.org/wiki/Capture/Webcam#OSX
maybe that FFMPEG doc is out of date.
