### ISSUE TITLE
ValueError: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by HarukiGrande** [scivision/PyLivestream#5]
Running:
`python3.6 /usr/local/bin/FileGlobLivestream.py youtube /music/ogg/vaporwave "*.ogg" -image vape.jpg -loop`

Causes:
```
Press Enter to go live on youtube.    Or Ctrl C to abort.
Traceback (most recent call last):
  File "/usr/local/bin/FileGlobLivestream.py", line 52, in <module>
    playonce(flist, p.image)
  File "/usr/local/bin/FileGlobLivestream.py", line 15, in playonce
    s = PyLivestream.FileIn(p.ini, p.site, f, loop=False, image=image)
  File "/usr/local/lib/python3.6/dist-packages/PyLivestream/__init__.py", line 419, in __init__
    self.stream = Livestream(ini, site, vidsource, image, loop, infn)
  File "/usr/local/lib/python3.6/dist-packages/PyLivestream/__init__.py", line 314, in __init__
    self.osparam()
  File "/usr/local/lib/python3.6/dist-packages/PyLivestream/__init__.py", line 121, in osparam
    self.res = get_resolution(self.infn)
  File "/usr/local/lib/python3.6/dist-packages/PyLivestream/__init__.py", line 79, in get_resolution
    res = (int(res[0].split('=')[-1]), int(res[1].split('=')[-1]))
ValueError: invalid literal for int() with base 10: ''
```

**Comment by scivision** [comment]
https://github.com/scivision/PyLivestream/releases/tag/v1.6.2 fixes this, thanks for your feedback!
