### ISSUE TITLE
TypeError: sequence item 0: expected str instance, PosixPath found

### ISSUE THREAD

**Issue by HarukiGrande** [scivision/PyLivestream#6]
Command: `python3.6 /usr/local/bin/FileGlobLivestream.py youtube /music/ogg/vaporwave "*.ogg" -image vape.jpg`

Error:
```
Press Enter to go live on youtube.    Or Ctrl C to abort.
WARNING:root:assuming 720p input.
Traceback (most recent call last):
  File "/usr/local/bin/FileGlobLivestream.py", line 56, in <module>
    playonce(flist, p.image)
  File "/usr/local/bin/FileGlobLivestream.py", line 19, in playonce
    s.golive()
  File "/usr/local/lib/python3.6/dist-packages/PyLivestream/__init__.py", line 123, in golive
    self.stream.golive()
  File "/usr/local/lib/python3.6/dist-packages/PyLivestream/__init__.py", line 42, in golive
    print('\n',' '.join(self.cmd))
TypeError: sequence item 0: expected str instance, PosixPath found
```

**Comment by scivision** [comment]
Thank you for your patience, https://github.com/scivision/PyLivestream/releases/tag/v1.6.3 fixes this issue.
As a result, Python >= 3.6 is now required (which you are already running) due to extensive type validation, to help prevent these issues in the future (and I found and fixed a few more bugs as a result).
