### ISSUE TITLE
Cannot install pylivestream via pip (python 3.7, Windows 10) 

### ISSUE THREAD

**Issue by Ari24-cb24** [scivision/PyLivestream#65]
**Describe the bug**
Hey there, I just want to install pylivestream via pip but doesnt seems like to work

Following error occurs:
```
Collecting pylivestream
  Using cached pylivestream-1.11.3.tar.gz (795 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\bobmy\appdata\local\programs\python\python37\python.exe' 'c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\bobmy\AppData\Local\Temp\pip-build-env-jpagtxxb\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel
       cwd: None
  Complete output (42 lines):
  Traceback (most recent call last):
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip\__main__.py", line 26, in <module>
      sys.exit(_main())
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\commands\__init__.py", line 105, in create_command
      module = importlib.import_module(module_path)
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
    File "<frozen importlib._bootstrap>", line 983, in _find_and_load
    File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 728, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\commands\install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\cli\req_command.py", line 18, in <module>
      from pip._internal.index.collector import LinkCollector
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip\_internal\index\collector.py", line 14, in <module>
      from pip._vendor import html5lib, requests
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\requests\__init__.py", line 125, in <module>
      from . import utils
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\requests\utils.py", line 25, in <module>
      from . import certs
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\requests\certs.py", line 15, in <module>
      from pip._vendor.certifi import where
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\certifi\__init__.py", line 1, in <module>
      from .core import contents, where
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip\_vendor\certifi\core.py", line 12, in <module>
      from importlib.resources import path as get_path, read_text
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\importlib\resources.py", line 11, in <module>
      from typing import Iterable, Iterator, Optional, Set, Union   # noqa: F401
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\typing.py", line 1357, in <module>
      class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
    File "c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\typing.py", line 1005, in __new__
      self._abc_registry = extra._abc_registry
  AttributeError: type object 'Callable' has no attribute '_abc_registry'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\bobmy\appdata\local\programs\python\python37\python.exe' 'c:\users\bobmy\appdata\local\programs\python\python37\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\bobmy\AppData\Local\Temp\pip-build-env-jpagtxxb\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel Check the logs for full command output.
```

**System Parameters**

* Operating system (Linux, Mac, Windows)
Windows 10

* FFmpeg version
ffmpeg version git-2020-08-24-3477feb

+ Newest pip version

**Comment by Ari24-cb24** [comment]
Okay, fixed it by uninstalling ``typing``, installing the package and installing ``typing`` again

**Comment by scivision** [comment]
Hi Ari, if it's this typing package: https://pypi.org/project/typing/  that's intended for Python 3.5 or older (i.e. end of life Python versions). It might be you have another package installed that is incorrectly downloading typing when typing is already built into all currently maintained Python versions.
